Traceback (most recent call last):
  File "/home/user/webapp/start_server.py", line 11, in <module>
    server = HTTPServer(('0.0.0.0', 8000), MyHandler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/start_server.py", line 11, in <module>
    server = HTTPServer(('0.0.0.0', 8000), MyHandler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/start_server.py", line 11, in <module>
    server = HTTPServer(('0.0.0.0', 8000), MyHandler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/home/user/webapp/start_server.py", line 11, in <module>
    server = HTTPServer(('0.0.0.0', 8000), MyHandler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.12/socketserver.py", line 478, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Server running on port 8000
19/Aug/2025 23:51:46 - "GET /contact-form.html HTTP/1.1" 200 -
19/Aug/2025 23:52:38 - "GET /contact-form.html HTTP/1.1" 200 -
19/Aug/2025 23:52:38 - "GET /assets/css/responsive.css HTTP/1.1" 200 -
19/Aug/2025 23:52:38 - "GET /assets/css/main.css HTTP/1.1" 200 -
19/Aug/2025 23:52:38 - "GET /assets/css/contact-form.css HTTP/1.1" 200 -
19/Aug/2025 23:52:38 - "GET /assets/js/contact-form.js HTTP/1.1" 200 -
19/Aug/2025 23:52:38 - code 404, message File not found
19/Aug/2025 23:52:38 - "GET /favicon.ico HTTP/1.1" 404 -
